spring:
  datasource:
    username: root
    password: 13545630179qq.
    url: jdbc:mysql://49.233.192.222/taobao?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
  redis:
    host: 49.233.192.222
    port: 6379
    password: 13545630179qq.
    timeout: 3000ms
    database: 0
    lettuce:
      pool:
        max-wait: 2000ms
        min-idle: 50
        max-idle: 100
        max-active: 200
excelDownloadUrl: http://49.233.192.222:8083/downloadExcel/
server:
  port: 8083
mybatis:
  mapper-locations: classpath:com/wusi/reimbursement/*Mapper.xml
 # configuration:
   # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
web:
  server: http://49.233.192.222:8083
upload:
  qiniu:
    bucket: daningmeng001
    accessKey: dJR8UzN31Iy8-yzRlBR3TBrkOe1RUdMNp0yZM_9k
    secretKey: l1uLDn9umthxCvqCrKRsAYqriucp0uIJciDcV4Jz
    host: http://www.photo.wearelie.com/

